# Designed to be merged with ./base.yml

volumes:
  traefik-dynamic:

services:
  habitat-config:
    volumes:
      - traefik-dynamic:/habitat-config/target/traefik
      - ./habitat-config:/habitat-config/source/${APP_MODULE_NAME}:ro
